global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'deepak.dev.mca22.du@gmail.com'
  smtp_auth_username: 'deepak.dev.mca22.du@gmail.com'
  smtp_auth_password: 'vrtnazbrfvwftkqh'
  smtp_require_tls: true

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'send-email'

receivers:
  - name: 'send-email'
    email_configs:
      - to: 'deepak.dev.mca22.du@gmail.com'

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal:
      - alertname
      - dev
      - instance
