global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['localhost:8000']  # Replace with your Django server address

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['localhost:9093']  # Alertmanager address

rule_files:
  - 'alert_rules.yml'  # Reference to the alert rules file
