# Generated by Django 5.0.6 on 2024-07-01 04:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=255)),
                ('Days_for_shipping_real', models.IntegerField()),
                ('Days_for_shipment_scheduled', models.IntegerField()),
                ('Benefit_per_order', models.FloatField()),
                ('Sales_per_customer', models.FloatField()),
                ('Delivery_Status', models.CharField(max_length=255)),
                ('Late_delivery_risk', models.IntegerField()),
                ('Category_Id', models.IntegerField()),
                ('Category_Name', models.CharField(max_length=255)),
                ('Customer_City', models.CharField(max_length=255)),
                ('Customer_Country', models.CharField(max_length=255)),
                ('Customer_Email', models.EmailField(max_length=254)),
                ('Customer_Fname', models.CharField(max_length=255)),
                ('Customer_Id', models.IntegerField()),
                ('Customer_Lname', models.CharField(max_length=255)),
                ('Customer_Password', models.CharField(max_length=255)),
                ('Customer_Segment', models.CharField(max_length=255)),
                ('Customer_State', models.CharField(max_length=255)),
                ('Customer_Street', models.CharField(max_length=255)),
                ('Customer_Zipcode', models.FloatField(null=True)),
                ('Department_Id', models.IntegerField()),
                ('Department_Name', models.CharField(max_length=255)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Market', models.CharField(max_length=255)),
                ('Order_City', models.CharField(max_length=255)),
                ('Order_Country', models.CharField(max_length=255, null=True)),
                ('Order_Customer_Id', models.FloatField(null=True)),
                ('order_date_DateOrders', models.CharField(max_length=255, null=True)),
                ('Order_Id', models.FloatField(null=True)),
                ('Order_Item_Cardprod_Id', models.FloatField(null=True)),
                ('Order_Item_Discount', models.FloatField(null=True)),
                ('Order_Item_Discount_Rate', models.FloatField(null=True)),
                ('Order_Item_Id', models.FloatField(null=True)),
                ('Order_Item_Product_Price', models.FloatField(null=True)),
                ('Order_Item_Profit_Ratio', models.FloatField(null=True)),
                ('Order_Item_Quantity', models.FloatField(null=True)),
                ('Sales', models.FloatField(null=True)),
                ('Order_Item_Total', models.FloatField(null=True)),
                ('Order_Profit_Per_Order', models.FloatField(null=True)),
                ('Order_Region', models.CharField(max_length=255, null=True)),
                ('Order_State', models.CharField(max_length=255, null=True)),
                ('Order_Status', models.CharField(max_length=255, null=True)),
                ('Order_Zipcode', models.FloatField(blank=True, null=True)),
                ('Product_Card_Id', models.FloatField(null=True)),
                ('Product_Category_Id', models.FloatField(null=True)),
                ('Product_Description', models.TextField(blank=True, null=True)),
                ('Product_Image', models.CharField(max_length=255, null=True)),
                ('Product_Name', models.CharField(max_length=255, null=True)),
                ('Product_Price', models.FloatField(null=True)),
                ('Product_Status', models.FloatField(null=True)),
                ('shipping_date_DateOrders', models.CharField(max_length=255, null=True)),
                ('Shipping_Mode', models.CharField(max_length=255, null=True)),
                ('tablename', models.CharField(max_length=50)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_details', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='data.orderdetails')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
